# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stek_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stek_app
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  target 'stek_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'stek_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stek_app-tvOS

  target 'stek_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
